config/routes.rb
Rails.application.routes.draw do

  post "/sendkeys" => "content#getJSON", :as => :getJSON
  post "/sendNo" => "content#sendPush", :as => :sendPush

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'admin/add_supplier_brand/:supplier_id/', to: 'admin/brands#add_supplier_brand', as: :add_supplier_brand
  get 'admin/new_supplier_brand/:supplier_id/', to: 'admin/brands#new_supplier_brand', as: :new_supplier_brand
  delete 'admin/remove_supplier_brand/:supplier_id/', to: 'admin/brands#remove_supplier_brand', as: :remove_supplier_brand

  delete 'admin/remove_supplier_category_part/:supplier_id/', to: 'admin/brands#remove_supplier_category_part', as: :remove_supplier_category_part

  post 'admin/add_supplier_category/:supplier_id/', to: 'admin/categories#add_supplier_category', as: :add_supplier_category
  get 'admin/new_supplier_category/:supplier_id/', to: 'admin/categories#new_supplier_category', as: :new_supplier_category
  delete 'admin/remove_supplier_category/:supplier_id/', to: 'admin/categories#remove_supplier_category', as: :remove_supplier_category

  post 'admin/add_user/:coupon_id/', to: 'admin/coupons#add_user', as: :add_user
  post 'admin/assign_all/:coupon_id/', to: 'admin/coupons#assign_all', as: :assign_all
  get 'admin/new_user_coupon/:coupon_id/', to: 'admin/coupons#new_user_coupon', as: :new_user_coupon
  delete 'admin/remove_coupon_user/:coupon_id/', to: 'admin/coupons#remove_coupon_user', as: :remove_coupon_user
  delete 'admin/category_sub_part_items/:category_sub_part_id', to: 'admin/category_part_items#destroy_category_sub_part', as: :remove_category_sub_part
  get 'open_image_to_process/:id', to: 'admin/item_types#open_image_to_process', as: :open_image_to_process
  
  get 'active/:id', to: 'admin/part_catalogs#active', as: :active
  get 'active_model/:id', to: 'admin/api_models#active_model', as: :active_model
  get 'active_part/:id', to: 'admin/api_parts#active_part', as: :active_part
  get 'open_image_to_process_part/:id', to: 'admin/api_parts#open_image_to_process_part', as: :open_image_to_process_part
  post 'create_hot_spot', to: 'admin/item_types#create_hot_spot', as: :create_hot_spot
  delete 'delete_hot_spot/:id', to: 'admin/item_types#delete_hot_spot', as: :delete_hot_spot
  
  get  '/', to: 'public/landing#index', as: :landing_index
  post  '/cotizar', to: 'public/landing#quote_create'
  get  '/quote', to: 'public/landing#quote', as: :landing_quote
  get  '/models', to: 'public/landing#models'
  get  '/get_models', to: 'public/landing#get_models'
  get  '/login_popup', to: 'public/landing#login_popup'
  get  '/get_fields', to: 'public/landing#get_fields'
  get  '/get_brands', to: 'public/landing#get_brands'
  get  '/get_date', to: 'public/landing#get_date'
  get  '/part_items', to: 'public/landing#part_items'
  get  '/category_parts', to: 'public/landing#category_parts'
  get  '/brands', to: 'public/landing#brands'
  post '/cotizar/ingreso', to: 'public/landing#quote_with_session', as: :landing_quote_with_session
  post '/login_with_address', to: 'public/landing#login_with_address', as: :landing_login_with_address
  post '/cotizar/registro', to: 'public/landing#quote_with_registration', as: :landing_quote_with_registration
  post '/cotizar/omniauth', to: 'public/landing#quote_with_omniauth', as: :landing_quote_with_omniauth
  post '/quote_with_current_user', to: 'public/landing#quote_with_current_user', as: :quote_with_current_user
  post '/create_quotation_request', to: 'public/landing#after_session_create_quotation_request'
  get 'get_item_sub_parts/', to: 'public/landing#category_sub_parts'
  get 'checkout/', to: 'public/landing#checkout'
  get 'cart/', to: 'public/landing#cart'
  get 'final_cart/', to: 'public/landing#final_cart'
  get 'remove_cart/', to: 'public/landing#remove_cart'
  get 'empty_cart/', to: 'public/landing#empty_cart'
  get 'update_quantity/', to: 'public/landing#update_quantity'
  get 'get_part_catalogs/', to: 'public/landing#get_part_catalogs'
  post 'checkout_process/', to: 'public/landing#checkout_process'
  post 'get_vehicle/', to: 'public/landing#get_vehicle'

  namespace :public, path: "" do 
    namespace :api do 
      resources :brands, only: [:index, :show]
      resources :models, only: [:index]
    end
  end

  namespace :api_data, path: "" do
    resources :catalogs
    resources :catalog_types
    resources :api_catalogs
    resources :api_models
    resources :api_sub_models
    resources :api_vehicles do
      collection do
        get 'user_vehicles'
      end
    end
    resources :api_vehicle_models
    resources :part_catalogs
    resources :api_parts do
      collection do
        get 'get_sub_part'
      end
    end
  end

  resources :category_part_items do
    get :autocomplete_category_part_item_name, :on => :collection
  end

  resources :vehicles
  resources :messages do 
    collection do 
      get :new_message
      post :send_message
    end
  end
  namespace :private, path: "" do 
    namespace :api do
      resources :quotations, only: [:index, :show]
      resources :quotation_requests do
        get "quotation_request_detail"
        resources :quotations, only: [:index, :show]
      end
      get 'get_user_vehicle', to: 'quotation_requests#get_user_vehicle'
      resources :users, only: [:index]
      #resources :suppliers_brands, only: [:index, :create, :destroy]

      get '/mi-perfil', to: 'profile#show', as: :profile_show
      post '/mi-perfil', to: 'profile#update', as: :profile_update
      get '/mi-perfil-edit', to: 'profile#edit', as: :profile_edit
      get '/new_address', to: 'profile#new_address', as: :new_address
      post '/create_address', to: 'profile#address_create', as: :create_address
      delete '/destroy_address/:id', to: 'profile#destroy_address', as: :destroy_address
      get '/update_password', to: 'profile#update_password', as: :update_password
      get '/edit_notify_preference', to: 'profile#edit_notify_preference', as: :edit_notify_preference
      post '/update_notify_preference', to: 'profile#update_notify_preference', as: :update_notify_preference
      get '/edit_address/:id', to: 'profile#edit_address', as: :edit_address
      post '/update_address/:id', to: 'profile#update_address', as: :update_address
      namespace :suppliers do 
        resources :brands, only: [:index, :create, :destroy, :new]
        resources :quotation_requests
        resources :quotations
        get '/approve_quote/:id', to: 'quotations#approve_quote', as: :approve_quote
      end
      get 'show_details/:id', to: 'quotations#show_details', as: :show_details
    end
  end

  namespace :employees, path: "" do
    resources :quotation_requests
    resources :quotations
  end

  devise_for :users, path: '/', path_names: { 
    sign_in: 'ingresar', 
    sign_out: 'salir', 
    registration: 'registro',
    sign_up: ''
  }, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    omniauth_callbacks: 'public/omniauth_callbacks',
    passwords: 'public/passwords'
  }
  devise_for :employees, path: '/', path_names: {
    sign_in: 'employee_sign_in',
    sign_out: 'employee_sign_out',
    registration: 'employee_registration'
  }, controllers: { 
    sessions: "employees/sessions",
    registrations: 'employees/registrations',
  }
  get '/employee_dashboard', to: 'employees/dashboard#index', as: :employee_dashboard

  get '/app', to: 'private/dashboard#index', as: :dashboard_index
  get '/notices', to: 'private/dashboard#notices', as: :notices
  get '/app/:some', to: 'private/dashboard#index'
  get '/app/:some/:some_again', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god/:how_the_fuck_i_do_a_wildcard', to: 'private/dashboard#index'

  resources :contacts

  resources :replies
  get 'how_its_works', to: 'pages#how_its_works'
  get 'about_us', to: 'pages#about_us'

  resources :questions do
    collection do
      get "show_pdf"
    end
    resources :replies
  end
  get 'all_questions', to: 'questions#all_questions'
  post 'filter_question', to: 'questions#filter_question'
  resources :quote_questions
  resources :referral_links
  resources :referral_users
  resources :orders do
    collection do
      get 'supplier_detail'
    end
  end

  resources :order_items, only:[] do
    get 'delivered'
    get 'approve'
    resources :courier_jobs, only: [:new, :create]
  end

  resources :courier_jobs, only: [:index, :edit, :update]
  resources :notifications, only: [:index]
  
  #****paypal******
  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
  get "paypal_payment" => "orders#paypal"

  #*****mercado_pago*** 
  get "mercado_proccess" => "orders#mercado_payment_proccess"
  post "/mercado_hook" => "orders#mercado_hook"
  get "mercado_return", to: "orders#mercado_return"

  #*****payment_notification****
  get "payment_method" => "orders#payment_method"
  get "payment_failed" => "orders#payment_failed"
  
  #******onepay****
  get "onepay" => "orders#onepay"
  get 'onepay_hook' => 'orders#onepay_hook'
  get 'commit' => 'orders#commit'

  #****carts****
  resources :carts
  get 'entrega', to: 'carts#entrega'
  post 'finalizar', to: 'carts#finalizar'
  get 'user_cart', to: 'carts#cart'
  get 'change_address', to: 'carts#change_address'
  get 'apply_coupon', to: 'carts#apply_coupon'
  get 'remove_coupon', to: 'carts#remove_coupon'
  get 'get_cities', to: 'carts#get_cities'
  delete 'delete_cart', to: 'carts#delete_cart'

end

app/controllers/private/api/base_controller.rb
class Private::Api::BaseController < ActionController::API
  include Devise::Controllers::Helpers

  before_action :authenticate_user!

  private 

  def set_pagination_defaults
    @per_page = params[:per_page]&.to_i || 10
    @page = params[:page]&.to_i || 1
  end
end

app/controllers/private/api/profile_controller.rb
class Private::Api::ProfileController < Private::BaseController
  
  layout :resolve_layout
  #********address START *********
  def new_address
  end

  def address_create
    @address = current_user.addresses.new(address_params)
    country = CS.states(:cl)
    @address.region = country[params['address']['region'].to_sym]
    if @address.save
      address_params["primary"].present? ? check_primary_address(@address.id) : ''
      flash[:success] = "Successfully added address!"
      redirect_to private_api_profile_show_path
    else
      flash[:error] = @address.errors.full_messages.join(", ")
      redirect_to private_api_profile_show_path
    end
  end

  def edit_address
    @address = Address.find(params[:id])
    @regions = CS.states(:cl)
    region_code = @regions.key(@address.region)
    @states = CS.states(:cl).values
    @cities = CS.cities(region_code)
  end

  def update_address
    @address = Address.find(params[:id])
    if @address.update(address_params.merge(primary: address_params["primary"].present?))
      address_params["primary"].present? ? check_primary_address(@address.id) : ''
      flash[:success] = "Successfully updated address!"
      redirect_to private_api_profile_show_path
    else
      flash[:error] = "Address could not update please try again later!"
      @address_errors = @address.errors.full_messages
      redirect_to private_api_profile_show_path
    end
  end

  def destroy_address
    @address = Address.find(params[:id])
    user = @address.addressable
    if @address.primary? && user.addresses.count >= 2
      user.addresses.where.not(id: @address.id).last.update_attributes(primary: true)
    end
    if @address.destroy
      flash[:success] = "Successfully deleted address!"
      redirect_to private_api_profile_show_path
    else
      flash[:error] = "Address could not be deleted!"
      redirect_to private_api_profile_show_path
    end
  end
  
  def check_primary_address id
    @not_primary = Address.where.not(id: id)
    if @not_primary
      @not_primary.update_all(primary: false)
      Address.where(id: id).update(primary: true)
    end
  end
  #***********address END ****
  
  def show

  end
  
  def edit
    @preference = UserNotifyPreference.find_by_user_id(current_user.id)
  end

  def update
    if current_user.valid_password?(params['user']['current_password'])
      user = current_user
      @notify = UserNotifyPreference.find_by_user_id(current_user.id)
      if user.update(which_params)

        if !params["notify"].nil?
          if @notify.update(new_conf_shipments: notify_preference_params["new_conf_shipments"].present?, promo_discount: notify_preference_params["promo_discount"].present?, payment: notify_preference_params["payment"].present?, dispatch_delivery: notify_preference_params["dispatch_delivery"].present?)
            flash[:success] = "Successfully update preferences!"
            redirect_to private_api_profile_show_path
          else
            flash[:error] = "Nothing updated in preferences!"
            redirect_to private_api_profile_show_path
          end
        else
          @notify.update(new_conf_shipments: false, promo_discount: false, payment: false, dispatch_delivery: false)
          flash[:success] = "Successfully updated preferences!"
          redirect_to private_api_profile_show_path
        end
      else
        flash[:error] = user.errors.full_messages
        redirect_to private_api_profile_show_path
      end
    else
      flash[:error] = "Current Password is not Correct"
      redirect_to private_api_profile_show_path
    end
  end

  def update_password

  end

  def edit_notify_preference
    # @preference = UserNotifyPreference.find_by_user_id(current_user.id)
  end
  def update_notify_preference
    # @notify = UserNotifyPreference.find_by_user_id(current_user.id)
    # if !params["notify"].nil?
    #   if @notify.update(new_conf_shipments: notify_preference_params["new_conf_shipments"].present?, promo_discount: notify_preference_params["promo_discount"].present?, payment: notify_preference_params["payment"].present?, dispatch_delivery: notify_preference_params["dispatch_delivery"].present?)
    #     flash[:success] = "Successfully update preferences!"
    #     redirect_to private_api_profile_show_path
    #   else
    #     flash[:error] = "Nothing updated in preferences!"
    #     redirect_to private_api_profile_show_path
    #   end
    # else
    #   @notify.update(new_conf_shipments: false, promo_discount: false, payment: false, dispatch_delivery: false)
    #   flash[:success] = "Successfully updated preferences!"
    #   redirect_to private_api_profile_show_path
    # end
  end
  private

  def profile_params
    params.require(:user).permit(:name, :last_name, :phone, :cellular, :office, :email, :dob, :password, :password_confirmation, addresses_attributes: [:id, :name, :street_address, :region, :city, :comuna, :phone, :_destroy])
  end

  def profile_params_without_password
    params.require(:user).permit(:name, :last_name,  :phone, :cellular, :office, :email, :dob)
  end

  def which_params
    if ((params[:user][:password_current].present? && current_user.valid_password?(params[:user][:password_current])) || params[:user][:password].present? || params[:user][:password_confirmation].present?)
        profile_params
    else
      profile_params_without_password
    end
  end
  
  def address_params
    params.require(:address).permit(:name, :street_address, :region, :city, :comuna, :phone, :_destroy, :primary)
  end

  def notify_preference_params
    params.require(:notify).permit(:new_conf_shipments, :promo_discount, :payment, :dispatch_delivery)
  end

  def resolve_layout
    if (action_name == "show")
      'v2_private'
    else
      'private'
    end
  end
end

app/controllers/private/api/suppliers/brands_controller.rb
class Private::Api::Suppliers::BrandsController < Private::BaseController
  before_action :set_brand, only: [:create, :destroy]

  def index
    @supplier_brands = current_supplier.brands
    @brands = @supplier_brands.pluck(:name, :id)
  end

  def new
    
  end

  def create
    if @brand
      current_supplier.brands << @brand
      flash[:success] = "Brand added successfully!"
      redirect_to private_api_suppliers_brands_path
    else
      flash[:error] = "Brand could not added!"
      redirect_to private_api_suppliers_brands_path
    end
  end

  def destroy
    if @brand
      current_supplier.brands.delete @brand
      flash[:success] = "Brand deleted successfully!"
      redirect_to private_api_suppliers_brands_path
    else
      flash[:error] = "Brand could not deleted!"
      redirect_to private_api_suppliers_brands_path
    end
  end

  private

  def current_supplier
    current_user.suppliers.first
  end

  def set_brand
    @brand = Brand.find_by(id: params[:brand_id] || params[:id])
  end
end

app/controllers/private/api/users_controller.rb
class Private::Api::UsersController < Private::Api::BaseController
  def index
    render status: :ok, json: current_user.profile_summary
  end
end

app/helpers/private/api/vehicles_helper.rb
module Private::Api::VehiclesHelper
end

app/views/private/api/profile/_edit.html.erb
<div class="" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog my-model-body modal-lg" role="document">
    <div class="enquiry_form main-model-content modal-content">
      <div class="modal-header editar  block-header bg-gd-primary">
        <h5 class="modal-title header_modtext text-white" id="exampleModalLabel">Cambiar Perfil</h5>
      </div>
     
      <div class="modal-body quotes_pad">
        <div class="style_popup"> 
          <%= form_for current_user,  url: private_api_profile_update_path, method: :post, class: "registration" do |f| %>
            <div class="form-group row">
              <div class="col-md-6">
                <label class="" for="example-text-input-invalid">Nombre:</label>
                <%= f.text_field :name, placeholder: "Nombre", required: true , class: "form-control", id: "example-text-input-invalid"%>
              </div>

              <div class="col-md-6">
                <label class="" for="example-text-input-invalid">Apellido:</label>
                <%= f.text_field :last_name, placeholder: "Apellido", required: true , class: "form-control", id: "example-text-input-invalid"%>
              </div>
            </div>

            <div class="form-group row">

              <div class="col-md-4">
                <label class="" for="example-text-input-invalid">Cumpleaños:</label>
                <%= f.date_field :dob, placeholder: "Cumpleaños", required: true , class: "form-control", id: "example-text-input-invalid"%>
              </div>

              <div class="col-md-4">
                <label class="" for="example-text-input-invalid">Casa:</label>
                <%= f.number_field :phone, required: true, class: "form-control", id: "example-text-input-invalid" , placeholder: "Casa"%>
              </div>

              <div class="col-md-4">
                <label class="" for="example-text-input-invalid">Celular:</label>
                <%= f.number_field :cellular, placeholder: "celular", required: true , class: "form-control", id: "example-text-input-invalid", placeholder: "Celular"%>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-6">
                <label class="" for="example-text-input-invalid">Oficina:</label>
                <%= f.number_field :office, required: true, class: "form-control", id: "example-text-input-invalid" , placeholder: "Oficina"%>
              </div>

              <div class="col-md-6">
                <label class="" for="example-text-input-invalid">Contraseña actual:</label>
                <%= f.password_field :current_password, placeholder: "****************" , class: "form-control", id: "example-text-input-invalid"%>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-md-6">
                <label class="" for="example-text-input-invalid">Nueva contraseña:</label>
                <%= f.password_field :password, placeholder: "****************", class: "form-control", id: "example-text-input-invalid"%>
                <p class="comment_txt">Tu contraseña debe contener un mínimo de 8 digitos con al menos una letra mayúscula y un número. </p>
              </div>

              <div class="col-md-6">
                <label class="" for="example-text-input-invalid">Confirmar nueva contraseña:</label>
                <%= f.password_field :password_confirmation, placeholder: "****************" , class: "form-control", id: "example-text-input-invalid"%>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-12">
                <div class="custom-control custom-checkbox custom-control-inline mb-5">
                  <%= check_box_tag 'notify[new_conf_shipments]', true, (@preference.new_conf_shipments ? true : false), class: "custom-control-input", id: "example-inline-checkbox1" %>
                  <label class="custom-control-label" for="example-inline-checkbox1">Nuevas Contizaciones y envíos</label>
                </div>
                <div class="custom-control custom-checkbox custom-control-inline mb-5">
                  <%= check_box_tag 'notify[new_conf_shipments]', true, (@preference.new_conf_shipments ? true : false), class: "custom-control-input", id: "example-inline-checkbox2" %>
                  <label class="custom-control-label" for="example-inline-checkbox2">Promociones y descuentos</label>
                </div>

                <div class="custom-control custom-checkbox custom-control-inline mb-5">
                  <%= check_box_tag 'notify[new_conf_shipments]', true, (@preference.new_conf_shipments ? true : false), class: "custom-control-input", id: "example-inline-checkbox1" %>
                  <label class="custom-control-label" for="example-inline-checkbox1">Pagos</label>
                </div>
                <div class="custom-control custom-checkbox custom-control-inline mb-5">
                  <%= check_box_tag 'notify[new_conf_shipments]', true, (@preference.new_conf_shipments ? true : false), class: "custom-control-input", id: "example-inline-checkbox2" %>
                  <label class="custom-control-label" for="example-inline-checkbox2">Despacho / Entrega</label>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-alt-success"><i class="fa fa-check"></i> Guardar cambios</button>
              <button type="button" class="btn btn-alt-secondary" data-dismiss="modal">Cerrar</button>
            </div>
          <%end%>
        </div>
        
      </div>
    </div>
  </div>
</div>
<style>
  .enquiry_form .modal-header {
    border-top-left-radius: 0 !important;
    border-top-right-radius: 0 !important;
  }
</style>

app/views/private/api/profile/_update_password.html.erb
<div class="" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog my-model-body" role="document">
    <div class=" enquiry_form main-model-content modal-content">
      <div class="modal-header editar">
        <h5 class="modal-title header_modtext" id="exampleModalLabel">Update Password</h5>
      </div>
      <span class="close-icon-top close" data-dismiss="modal" aria-label="Close"><img src="<%= image_path('close-icon.png')%>"></span>
      <div class="modal-body">
        <div class="popup">
          <%= form_for current_user,  url: private_api_profile_update_path, method: :post, class: "registration" do |f| %>
            <ul class="model_inputs">
              <li>
                Contraseña:
              </li>
              <li>
                <%= f.password_field :password, placeholder: "****************", required: true %>
              </li>
            </ul>
             <ul class="model_inputs">
              <li>
                Confirmar contraseña:
              </li>
              <li>
                <%= f.password_field :password_confirmation, placeholder: "****************", required: true %>
              </li>
            </ul>
            <%= f.submit "Update", class: "model-footer-btn edit-model-btn", :"data-turbolinks" => false %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/private/api/profile/edit.js.erb
$("#profile-edit-modal").html("<%= j(render 'edit')%>")
$("#profile-edit-modal").modal("show")

$('#closeModal').click(function(){
  $('#profile-edit-modal').modal("hide");
});

app/views/private/api/profile/show.html.erb
<!-- Main Container -->
<main id="main-container">
  <!-- Hero -->
  <div class="bg-gd-dusk">
    <div class="bg-black-op-25">
      <div class="content content-top content-full text-center">
        <div class="mb-20">
          <a class="img-link" href="be_pages_ecom_customer.html">
            <img class="img-avatar img-avatar-thumb" src="<%= asset_path('avatar15.jpg') %>" alt="">
          </a>
        </div>
        <h1 class="h3 text-white font-w700 mb-10">
          <%= current_user.name%> <i class="fa fa-star text-warning"></i>
        </h1>
      </div>
    </div>
  </div>
  <!-- END Hero -->

  <!-- Breadcrumb -->
  
  <!-- END Breadcrumb -->

  <!-- Page Content -->
  <div class="content">
    <!-- Overview -->
    <h2 class="content-heading">Visión general</h2>
    <div class="row gutters-tiny">
      <!-- Orders -->
      <div class="col-md-6 col-xl-4">
        <a class="block block-rounded block-link-shadow" href="javascript:void(0)">
          <div class="block-content block-content-full block-sticky-options">
            <div class="block-options">
              <div class="block-options-item">
                <i class="fa fa-line-chart fa-2x text-body-bg-dark"></i>
              </div>
            </div>
            <div class="py-20 text-center">
              <div class="font-size-h2 font-w700 mb-0" data-toggle="countTo" data-to="<%= current_user.orders.count%>">0</div>
              <div class="font-size-sm font-w600 text-uppercase text-muted">Pedidos</div>
            </div>
          </div>
        </a>
      </div>
      <!-- END Orders -->

      <!-- In Cart -->
      <div class="col-md-6 col-xl-4">
        <a class="block block-rounded block-link-shadow" href="javascript:void(0)">
          <div class="block-content block-content-full block-sticky-options">
            <div class="block-options">
              <div class="block-options-item">
                <i class="fa fa-shopping-cart fa-2x text-body-bg-dark"></i>
              </div>
            </div>
            <div class="py-20 text-center">
              <div class="font-size-h2 font-w700 mb-0" data-toggle="countTo" data-to="<%= current_user.cart.cart_items.count rescue ''%>">0</div>
              <div class="font-size-sm font-w600 text-uppercase text-muted">En el carrito</div>
            </div>
          </div>
        </a>
      </div>
      <!-- END In Cart -->

      <!-- Edit Customer -->
      <div class="col-md-6 col-xl-4">
        <%=link_to  private_api_profile_edit_path, remote: true, class: "block block-rounded block-link-shadow" do %>
          <div class="block-content block-content-full block-sticky-options">
            <div class="block-options">
              <div class="block-options-item">
                <i class="fa fa-user fa-2x text-info-light"></i>
              </div>
            </div>
            <div class="py-20 text-center">
              <div class="font-size-h2 font-w700 mb-0 text-info">
                <i class="fa fa-pencil"></i>
              </div>
              <div class="font-size-sm font-w600 text-uppercase text-muted">
                Editar Usuario
              </div>
            </div>
          </div>
        <%end%>
      </div>
      <!-- END Edit Customer -->
    </div>

    <h2 class="content-heading">Direcciones
    <%=link_to private_api_new_address_path, class: "btn btn-success mr-5 mb-5 right", remote: true do %>
      <i class="fa fa-plus mr-5"></i> Añadir dirección
    <% end %>
    </h2>

    <div class="row row-deck gutters-tiny">
      <!-- Billing Address -->
      <%current_user.addresses.each do |address|%>
        <div class="col-md-6">
          <div class="block block-rounded">
            <div class="block-header block-header-default">
            <h3 class="block-title">Dirección de residencia</h3>
            <div class="block-options">
              <%=link_to private_api_destroy_address_path(address.id),class: "btn-block-option", method: 'delete', :data => {:confirm => '¿Estás seguro?', title: "Alerta de confirmación!"} do %>
                <i class="fa fa-times text-danger"></i>
              <% end %>
            </div>
            <div class="block-options">
              <%=link_to private_api_edit_address_path(address.id), class: "btn-block-option", remote: true do %>
                <i class="fa fa-pencil"></i>
              <% end %>
            </div>
          </div>
          <div class="block-content">
            <div class="font-size-lg text-black mb-5"><%= address.name%></div>
            <address>
              <%= address.street_address%><br>
              <%= address.city%><br>
              <%= address.region%><br><br>
              <i class="fa fa-phone mr-5"></i> <%= address.phone%><br>
              <% if address.primary? %>
                <span class="badge badge-success">Primary</span>
              <% end %>
            </address>
          </div>
        </div>
      </div>
      <%end%>
    </div>
    <!-- END Addresses -->

    <!-- Cart -->
    
    <!-- END Cart -->

    <!-- Past Orders -->
    
  </div>

</main>

<div class="modal" id="profile-edit-modal">
  <div class="ant-modal-mask"></div>
</div>

<div class="modal" id="address-new-modal">
  <div class="ant-modal-mask"></div>
</div>

<div class="modal" id="address-edit-modal">
  <div class="ant-modal-mask"></div>
</div>
<style>
  .right{
    float: right;
  }
</style>