config/routes.rb
Rails.application.routes.draw do

  post "/sendkeys" => "content#getJSON", :as => :getJSON
  post "/sendNo" => "content#sendPush", :as => :sendPush

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'admin/add_supplier_brand/:supplier_id/', to: 'admin/brands#add_supplier_brand', as: :add_supplier_brand
  get 'admin/new_supplier_brand/:supplier_id/', to: 'admin/brands#new_supplier_brand', as: :new_supplier_brand
  delete 'admin/remove_supplier_brand/:supplier_id/', to: 'admin/brands#remove_supplier_brand', as: :remove_supplier_brand

  delete 'admin/remove_supplier_category_part/:supplier_id/', to: 'admin/brands#remove_supplier_category_part', as: :remove_supplier_category_part

  post 'admin/add_supplier_category/:supplier_id/', to: 'admin/categories#add_supplier_category', as: :add_supplier_category
  get 'admin/new_supplier_category/:supplier_id/', to: 'admin/categories#new_supplier_category', as: :new_supplier_category
  delete 'admin/remove_supplier_category/:supplier_id/', to: 'admin/categories#remove_supplier_category', as: :remove_supplier_category

  post 'admin/add_user/:coupon_id/', to: 'admin/coupons#add_user', as: :add_user
  post 'admin/assign_all/:coupon_id/', to: 'admin/coupons#assign_all', as: :assign_all
  get 'admin/new_user_coupon/:coupon_id/', to: 'admin/coupons#new_user_coupon', as: :new_user_coupon
  delete 'admin/remove_coupon_user/:coupon_id/', to: 'admin/coupons#remove_coupon_user', as: :remove_coupon_user
  delete 'admin/category_sub_part_items/:category_sub_part_id', to: 'admin/category_part_items#destroy_category_sub_part', as: :remove_category_sub_part
  get 'open_image_to_process/:id', to: 'admin/item_types#open_image_to_process', as: :open_image_to_process
  
  get 'active/:id', to: 'admin/part_catalogs#active', as: :active
  get 'active_model/:id', to: 'admin/api_models#active_model', as: :active_model
  get 'active_part/:id', to: 'admin/api_parts#active_part', as: :active_part
  get 'open_image_to_process_part/:id', to: 'admin/api_parts#open_image_to_process_part', as: :open_image_to_process_part
  post 'create_hot_spot', to: 'admin/item_types#create_hot_spot', as: :create_hot_spot
  delete 'delete_hot_spot/:id', to: 'admin/item_types#delete_hot_spot', as: :delete_hot_spot
  
  get  '/', to: 'public/landing#index', as: :landing_index
  post  '/cotizar', to: 'public/landing#quote_create'
  get  '/quote', to: 'public/landing#quote', as: :landing_quote
  get  '/models', to: 'public/landing#models'
  get  '/get_models', to: 'public/landing#get_models'
  get  '/login_popup', to: 'public/landing#login_popup'
  get  '/get_fields', to: 'public/landing#get_fields'
  get  '/get_brands', to: 'public/landing#get_brands'
  get  '/get_date', to: 'public/landing#get_date'
  get  '/part_items', to: 'public/landing#part_items'
  get  '/category_parts', to: 'public/landing#category_parts'
  get  '/brands', to: 'public/landing#brands'
  post '/cotizar/ingreso', to: 'public/landing#quote_with_session', as: :landing_quote_with_session
  post '/login_with_address', to: 'public/landing#login_with_address', as: :landing_login_with_address
  post '/cotizar/registro', to: 'public/landing#quote_with_registration', as: :landing_quote_with_registration
  post '/cotizar/omniauth', to: 'public/landing#quote_with_omniauth', as: :landing_quote_with_omniauth
  post '/quote_with_current_user', to: 'public/landing#quote_with_current_user', as: :quote_with_current_user
  post '/create_quotation_request', to: 'public/landing#after_session_create_quotation_request'
  get 'get_item_sub_parts/', to: 'public/landing#category_sub_parts'
  get 'checkout/', to: 'public/landing#checkout'
  get 'cart/', to: 'public/landing#cart'
  get 'final_cart/', to: 'public/landing#final_cart'
  get 'remove_cart/', to: 'public/landing#remove_cart'
  get 'empty_cart/', to: 'public/landing#empty_cart'
  get 'update_quantity/', to: 'public/landing#update_quantity'
  get 'get_part_catalogs/', to: 'public/landing#get_part_catalogs'
  post 'checkout_process/', to: 'public/landing#checkout_process'
  post 'get_vehicle/', to: 'public/landing#get_vehicle'

  namespace :public, path: "" do 
    namespace :api do 
      resources :brands, only: [:index, :show]
      resources :models, only: [:index]
    end
  end

  namespace :api_data, path: "" do
    resources :catalogs
    resources :catalog_types
    resources :api_catalogs
    resources :api_models
    resources :api_sub_models
    resources :api_vehicles do
      collection do
        get 'user_vehicles'
      end
    end
    resources :api_vehicle_models
    resources :part_catalogs
    resources :api_parts do
      collection do
        get 'get_sub_part'
      end
    end
  end

  resources :category_part_items do
    get :autocomplete_category_part_item_name, :on => :collection
  end

  resources :vehicles
  resources :messages do 
    collection do 
      get :new_message
      post :send_message
    end
  end
  namespace :private, path: "" do 
    namespace :api do
      resources :quotations, only: [:index, :show]
      resources :quotation_requests do
        get "quotation_request_detail"
        resources :quotations, only: [:index, :show]
      end
      get 'get_user_vehicle', to: 'quotation_requests#get_user_vehicle'
      resources :users, only: [:index]
      #resources :suppliers_brands, only: [:index, :create, :destroy]

      get '/mi-perfil', to: 'profile#show', as: :profile_show
      post '/mi-perfil', to: 'profile#update', as: :profile_update
      get '/mi-perfil-edit', to: 'profile#edit', as: :profile_edit
      get '/new_address', to: 'profile#new_address', as: :new_address
      post '/create_address', to: 'profile#address_create', as: :create_address
      delete '/destroy_address/:id', to: 'profile#destroy_address', as: :destroy_address
      get '/update_password', to: 'profile#update_password', as: :update_password
      get '/edit_notify_preference', to: 'profile#edit_notify_preference', as: :edit_notify_preference
      post '/update_notify_preference', to: 'profile#update_notify_preference', as: :update_notify_preference
      get '/edit_address/:id', to: 'profile#edit_address', as: :edit_address
      post '/update_address/:id', to: 'profile#update_address', as: :update_address
      namespace :suppliers do 
        resources :brands, only: [:index, :create, :destroy, :new]
        resources :quotation_requests
        resources :quotations
        get '/approve_quote/:id', to: 'quotations#approve_quote', as: :approve_quote
      end
      get 'show_details/:id', to: 'quotations#show_details', as: :show_details
    end
  end

  namespace :employees, path: "" do
    resources :quotation_requests
    resources :quotations
  end

  devise_for :users, path: '/', path_names: { 
    sign_in: 'ingresar', 
    sign_out: 'salir', 
    registration: 'registro',
    sign_up: ''
  }, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    omniauth_callbacks: 'public/omniauth_callbacks',
    passwords: 'public/passwords'
  }
  devise_for :employees, path: '/', path_names: {
    sign_in: 'employee_sign_in',
    sign_out: 'employee_sign_out',
    registration: 'employee_registration'
  }, controllers: { 
    sessions: "employees/sessions",
    registrations: 'employees/registrations',
  }
  get '/employee_dashboard', to: 'employees/dashboard#index', as: :employee_dashboard

  get '/app', to: 'private/dashboard#index', as: :dashboard_index
  get '/notices', to: 'private/dashboard#notices', as: :notices
  get '/app/:some', to: 'private/dashboard#index'
  get '/app/:some/:some_again', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god/:how_the_fuck_i_do_a_wildcard', to: 'private/dashboard#index'

  resources :contacts

  resources :replies
  get 'how_its_works', to: 'pages#how_its_works'
  get 'about_us', to: 'pages#about_us'

  resources :questions do
    collection do
      get "show_pdf"
    end
    resources :replies
  end
  get 'all_questions', to: 'questions#all_questions'
  post 'filter_question', to: 'questions#filter_question'
  resources :quote_questions
  resources :referral_links
  resources :referral_users
  resources :orders do
    collection do
      get 'supplier_detail'
    end
  end

  resources :order_items, only:[] do
    get 'delivered'
    get 'approve'
    resources :courier_jobs, only: [:new, :create]
  end

  resources :courier_jobs, only: [:index, :edit, :update]
  resources :notifications, only: [:index]
  
  #****paypal******
  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
  get "paypal_payment" => "orders#paypal"

  #*****mercado_pago*** 
  get "mercado_proccess" => "orders#mercado_payment_proccess"
  post "/mercado_hook" => "orders#mercado_hook"
  get "mercado_return", to: "orders#mercado_return"

  #*****payment_notification****
  get "payment_method" => "orders#payment_method"
  get "payment_failed" => "orders#payment_failed"
  
  #******onepay****
  get "onepay" => "orders#onepay"
  get 'onepay_hook' => 'orders#onepay_hook'
  get 'commit' => 'orders#commit'

  #****carts****
  resources :carts
  get 'entrega', to: 'carts#entrega'
  post 'finalizar', to: 'carts#finalizar'
  get 'user_cart', to: 'carts#cart'
  get 'change_address', to: 'carts#change_address'
  get 'apply_coupon', to: 'carts#apply_coupon'
  get 'remove_coupon', to: 'carts#remove_coupon'
  get 'get_cities', to: 'carts#get_cities'
  delete 'delete_cart', to: 'carts#delete_cart'

end

app/controllers/employees/dashboard_controller.rb
class Employees::DashboardController < Employees::BaseController
  
  def index

  end
end

app/controllers/private/api/base_controller.rb
class Private::Api::BaseController < ActionController::API
  include Devise::Controllers::Helpers

  before_action :authenticate_user!

  private 

  def set_pagination_defaults
    @per_page = params[:per_page]&.to_i || 10
    @page = params[:page]&.to_i || 1
  end
end

app/controllers/private/api/profile_controller.rb
class Private::Api::ProfileController < Private::BaseController
  
  layout :resolve_layout
  #********address START *********
  def new_address
  end

  def address_create
    @address = current_user.addresses.new(address_params)
    country = CS.states(:cl)
    @address.region = country[params['address']['region'].to_sym]
    if @address.save
      address_params["primary"].present? ? check_primary_address(@address.id) : ''
      flash[:success] = "Successfully added address!"
      redirect_to private_api_profile_show_path
    else
      flash[:error] = @address.errors.full_messages.join(", ")
      redirect_to private_api_profile_show_path
    end
  end

  def edit_address
    @address = Address.find(params[:id])
    @regions = CS.states(:cl)
    region_code = @regions.key(@address.region)
    @states = CS.states(:cl).values
    @cities = CS.cities(region_code)
  end

  def update_address
    @address = Address.find(params[:id])
    if @address.update(address_params.merge(primary: address_params["primary"].present?))
      address_params["primary"].present? ? check_primary_address(@address.id) : ''
      flash[:success] = "Successfully updated address!"
      redirect_to private_api_profile_show_path
    else
      flash[:error] = "Address could not update please try again later!"
      @address_errors = @address.errors.full_messages
      redirect_to private_api_profile_show_path
    end
  end

  def destroy_address
    @address = Address.find(params[:id])
    user = @address.addressable
    if @address.primary? && user.addresses.count >= 2
      user.addresses.where.not(id: @address.id).last.update_attributes(primary: true)
    end
    if @address.destroy
      flash[:success] = "Successfully deleted address!"
      redirect_to private_api_profile_show_path
    else
      flash[:error] = "Address could not be deleted!"
      redirect_to private_api_profile_show_path
    end
  end
  
  def check_primary_address id
    @not_primary = Address.where.not(id: id)
    if @not_primary
      @not_primary.update_all(primary: false)
      Address.where(id: id).update(primary: true)
    end
  end
  #***********address END ****
  
  def show

  end
  
  def edit
    @preference = UserNotifyPreference.find_by_user_id(current_user.id)
  end

  def update
    if current_user.valid_password?(params['user']['current_password'])
      user = current_user
      @notify = UserNotifyPreference.find_by_user_id(current_user.id)
      if user.update(which_params)

        if !params["notify"].nil?
          if @notify.update(new_conf_shipments: notify_preference_params["new_conf_shipments"].present?, promo_discount: notify_preference_params["promo_discount"].present?, payment: notify_preference_params["payment"].present?, dispatch_delivery: notify_preference_params["dispatch_delivery"].present?)
            flash[:success] = "Successfully update preferences!"
            redirect_to private_api_profile_show_path
          else
            flash[:error] = "Nothing updated in preferences!"
            redirect_to private_api_profile_show_path
          end
        else
          @notify.update(new_conf_shipments: false, promo_discount: false, payment: false, dispatch_delivery: false)
          flash[:success] = "Successfully updated preferences!"
          redirect_to private_api_profile_show_path
        end
      else
        flash[:error] = user.errors.full_messages
        redirect_to private_api_profile_show_path
      end
    else
      flash[:error] = "Current Password is not Correct"
      redirect_to private_api_profile_show_path
    end
  end

  def update_password

  end

  def edit_notify_preference
    # @preference = UserNotifyPreference.find_by_user_id(current_user.id)
  end
  def update_notify_preference
    # @notify = UserNotifyPreference.find_by_user_id(current_user.id)
    # if !params["notify"].nil?
    #   if @notify.update(new_conf_shipments: notify_preference_params["new_conf_shipments"].present?, promo_discount: notify_preference_params["promo_discount"].present?, payment: notify_preference_params["payment"].present?, dispatch_delivery: notify_preference_params["dispatch_delivery"].present?)
    #     flash[:success] = "Successfully update preferences!"
    #     redirect_to private_api_profile_show_path
    #   else
    #     flash[:error] = "Nothing updated in preferences!"
    #     redirect_to private_api_profile_show_path
    #   end
    # else
    #   @notify.update(new_conf_shipments: false, promo_discount: false, payment: false, dispatch_delivery: false)
    #   flash[:success] = "Successfully updated preferences!"
    #   redirect_to private_api_profile_show_path
    # end
  end
  private

  def profile_params
    params.require(:user).permit(:name, :last_name, :phone, :cellular, :office, :email, :dob, :password, :password_confirmation, addresses_attributes: [:id, :name, :street_address, :region, :city, :comuna, :phone, :_destroy])
  end

  def profile_params_without_password
    params.require(:user).permit(:name, :last_name,  :phone, :cellular, :office, :email, :dob)
  end

  def which_params
    if ((params[:user][:password_current].present? && current_user.valid_password?(params[:user][:password_current])) || params[:user][:password].present? || params[:user][:password_confirmation].present?)
        profile_params
    else
      profile_params_without_password
    end
  end
  
  def address_params
    params.require(:address).permit(:name, :street_address, :region, :city, :comuna, :phone, :_destroy, :primary)
  end

  def notify_preference_params
    params.require(:notify).permit(:new_conf_shipments, :promo_discount, :payment, :dispatch_delivery)
  end

  def resolve_layout
    if (action_name == "show")
      'v2_private'
    else
      'private'
    end
  end
end

app/controllers/private/api/suppliers/brands_controller.rb
class Private::Api::Suppliers::BrandsController < Private::BaseController
  before_action :set_brand, only: [:create, :destroy]

  def index
    @supplier_brands = current_supplier.brands
    @brands = @supplier_brands.pluck(:name, :id)
  end

  def new
    
  end

  def create
    if @brand
      current_supplier.brands << @brand
      flash[:success] = "Brand added successfully!"
      redirect_to private_api_suppliers_brands_path
    else
      flash[:error] = "Brand could not added!"
      redirect_to private_api_suppliers_brands_path
    end
  end

  def destroy
    if @brand
      current_supplier.brands.delete @brand
      flash[:success] = "Brand deleted successfully!"
      redirect_to private_api_suppliers_brands_path
    else
      flash[:error] = "Brand could not deleted!"
      redirect_to private_api_suppliers_brands_path
    end
  end

  private

  def current_supplier
    current_user.suppliers.first
  end

  def set_brand
    @brand = Brand.find_by(id: params[:brand_id] || params[:id])
  end
end

app/controllers/private/api/users_controller.rb
class Private::Api::UsersController < Private::Api::BaseController
  def index
    render status: :ok, json: current_user.profile_summary
  end
end

app/helpers/private/api/vehicles_helper.rb
module Private::Api::VehiclesHelper
end

app/views/private/dashboard/index.html.erb
<main id="main-container">
  <div class="content">
    <div class="content-heading">       
    </div>

  
  <div class="content-heading">
    <div class="dropdown float-right mr-5">
      <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" id="ecom-orders-filter-drop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= get_status_lable(params[:status]) %>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="ecom-orders-filter-drop">
        <a class="dropdown-item" href="<%= dashboard_index_path(:status => 'confirmation_pending', :time => params[:time]) %>">
          <i class="fa fa-fw fa-spinner fa-spin text-warning mr-5"></i>Pendientes
        </a>
        <a class="dropdown-item" href="<%= dashboard_index_path(:status => 'in_process', :time => params[:time]) %>">
          <i class="fa fa-fw fa-refresh fa-spin text-info mr-5"></i>En proceso
        </a>
        <a class="dropdown-item" href="<%= dashboard_index_path(:status => 'delivered', :time => params[:time]) %>">
          <i class="fa fa-fw fa-check text-success mr-5"></i>Entregado
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item active" href="<%= dashboard_index_path(:status => 'all', :time => params[:time]) %>">
          <i class="fa fa-fw fa-circle-o mr-5"></i>Todas
        </a>
      </div>
    </div>
    <div class="dropdown float-right">
      <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" id="ecom-orders-drop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= get_time_lable(params[:time]) %>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="ecom-orders-drop">
        <a class="dropdown-item active" href="<%= dashboard_index_path(:time => 'today', :status => params[:status]) %>">
          <i class="fa fa-fw fa-calendar mr-5"></i>Hoy
        </a>
        <a class="dropdown-item" href="<%= dashboard_index_path(:time => 'week', :status => params[:status]) %>">
          <i class="fa fa-fw fa-calendar mr-5"></i>Esta semana
        </a>
        <a class="dropdown-item" href="<%= dashboard_index_path(:time => 'month', :status => params[:status]) %>">
          <i class="fa fa-fw fa-calendar mr-5"></i>Este Mes
        </a>
        <a class="dropdown-item" href="<%= dashboard_index_path(:time => 'year', :status => params[:status]) %>">
          <i class="fa fa-fw fa-calendar mr-5"></i>Este Año
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="<%= dashboard_index_path(:time => 'all', :status => params[:status]) %>">
          <i class="fa fa-fw fa-circle-o mr-5"></i>Todas
        </a>
      </div>
    </div>
      Últimas Ordenes
  </div>
    <div class="block block-rounded">
      <div class="block-content">
        <div class="table-responsive">
          <table class="table table-borderless table-striped">
            <thead>
              <tr>
                <th class="text-center">ID</th>
                <th class="text-justify" style="width: 1px;">Estado</th>
                <th class="text-center">Fecha</th>
                <th class="text-center">Productos</th>
                <th class="text-center" style="white-space:nowrap;">Cantidad Total</th>
              </tr>
            </thead>
            <tbody>
              <% unless @orders.blank? %>
                <%@orders.uniq.each do |order|%>
                  <tr>
                    <td class="text-center">
                      <%= link_to "#{order.id}", order_path(order.id), class: 'font-w600'%>
                    </td>
                    <td class="text-justify">
                      <span class="badge badge-<%= bootstrap_class_for order.status %> <%= order.status%> "><%= translate_for(order.status)%></span>
                    </td>
                    <td class="text-center"><%= order.purchased_at.strftime('%d/%m/%Y') rescue ''%></td>
                    <td class="text-center">
                      <a href="javascript:void(0)"><%= order.order_items.count%></a>
                    </td>
                    <td class="text-center">
                      <%if order.total_pay_amount.present? %>
                      <% price =  number_with_precision(order.total_pay_amount, :precision => 2, :delimiter => '.', strip_insignificant_zeros: true) %>
                      <%end%>
                      <span class="text-black">$ <%= order.total_pay_amount.present? ? price  : "0" %></span>
                    </td>
                  </tr>
                <%end%>
              <%else%>
                <tr><td class="text-center" colspan="6">ningún record fue encontrado</td></tr>  
              <%end%>
            </tbody>
          </table>
          <div class="pag_right_pa">
            <%= paginate @orders rescue '' %>
          </div>
        </div>
      </div>
    </div>
    <%unless current_user.addresses.present?%>
      <div class="modal fade" id="modal-onboarding" tabindex="-1" role="dialog" aria-labelledby="modal-onboarding" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-popout" role="document">
          <div class="modal-content rounded">
            <div class="block block-rounded block-transparent mb-0 bg-pattern" style="background-image: url('assets/media/various/bg-pattern-inverse.png');">
              <div class="block-header justify-content-end">
              </div>
              <div class="block-content block-content-full">
                <div class="js-slider slick-dotted-inner" data-dots="true" data-arrows="false" data-infinite="false">
                  <div class="pb-50 welcome">
                    <div class="row justify-content-center text-center">
                      <div class="col-md-10 col-lg-8">
                        <i class="si si-fire fa-4x text-primary"></i>
                        <h3 class="font-size-h2 font-w300 mt-20">Welcome to Codebase!</h3>
                        <p class="text-muted">
                          Este es un modo que puede mostrar a sus usuarios cuando inician sesión en su panel de control. Es un gran lugar para darles la bienvenida y presentarles su aplicación y su funcionalidad.
                        </p>
                        <button type="button" class="btn btn-sm btn-hero btn-noborder btn-primary mb-10 mx-5 key_feature">
                          Key features <i class="fa fa-arrow-right ml-5"></i>
                        </button>
                      </div>
                    </div>
                  </div>
                  <div class="slick-slide pb-50 backup">
                    <div class="row justify-content-center">
                      <div class="col-md-10 col-lg-8">
                        <h3 class="font-size-h2 font-w300 mb-5">Backup</h3>
                        <p class="text-muted">
                          Las copias de seguridad se realizan con cada nuevo cambio para garantizar una total tranquilidad. Se mantienen seguros para restauraciones inmediatas.
                        </p>
                        <h3 class="font-size-h2 font-w300 mb-5">Invoices</h3>
                        <p class="text-muted">
                          Se envían automáticamente a sus clientes con la finalización de cada proyecto, para que no tenga que preocuparse por recibir el pago.
                        </p>
                        <div class="text-center">
                          <button type="button" class="btn btn-sm btn-hero btn-noborder btn-primary mb-10 mx-5 complete">
                            Complete Profile <i class="fa fa-arrow-right ml-5"></i>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="slick-slide pb-50 finally">
                    <div class="row justify-content-center text-center">
                      <div class="col-md-10 col-lg-8">
                        <i class="si si-note fa-4x text-primary"></i>
                        <h3 class="font-size-h2 font-w300 mt-20 finally">Por último, háganos saber su dirección.</h3>
                        <%= form_tag private_api_create_address_path, method: :post do |f| %>
                          <div class="form-group row">
                            <div class="col-md-6">
                              <label class="" for="example-text-input-invalid">Nombre de la dirección:</label>
                              <%= text_field_tag 'address[name]', '', placeholder: "Nombre de la dirección", required: true , class: "form-control"%>
                            </div>

                            <div class="col-md-6">
                              <label class="" for="example-text-input-invalid">Calle Dirección:</label>
                              <%= text_field_tag 'address[street_address]', '', placeholder: "Calle Dirección", required: true , class: "form-control"%>
                            </div>
                          </div>
                          <div class="form-group row">
                            <div class="col-md-6">
                              <label class="" for="example-text-input-invalid">Añadir Región:</label>
                              <% a = CS.states(:cl)%>
                              <%= select_tag 'address[region]', options_for_select(a.collect{|p| [p[1], p[1]]}, ''), placeholder: "Añadir Región", required: true , class: "form-control region"%>
                            </div>

                            <div class="col-md-6">
                              <label class="" for="example-text-input-invalid">Ciudad:</label>
                              <%= select_tag 'address[city]', '', placeholder: "Add Ciudad", required: true , class: "form-control"%>
                            </div>
                          </div>

                          <div class="form-group row">
                            <div class="col-md-6">
                              <label class="" for="example-text-input-invalid">Comuna:</label>
                              <%= text_field_tag 'address[comuna]', '', placeholder: "Add Comuna", required: true , class: "form-control"%>
                            </div>
                            <div class="col-md-6">
                              <label class="" for="example-text-input-invalid">Teléfono:</label>
                              <%= number_field_tag 'address[phone]', '', placeholder: "Teléfono", required: true , class: "form-control"%>
                            </div>
                          </div>

                          <div class="form-group row">
                            <div class="col-md-6" style="text-align: left">
                              <label class="primary-text" for="example-text-input-invalid">Primaria:</label>
                              <%= check_box_tag 'address[primary]', placeholder: "Añadir Primaria", required: true , class: "form-control"%>
                            </div>
                          </div>

                          <div class="modal-footer form-btn-full">
                            <button type="submit" class="btn btn-sm btn-hero btn-noborder btn-success mb-10 mx-5"><i class="fa fa-check"></i> Guardar cambios y empezar</button>
                          </div>
                          
                        <%end%>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <%end%>
</main>

<script>
  
  $(function () {
     $('.modal').modal({
      show:true,
      keyboard: false,
      backdrop: 'static'
    });
  });

  $('document').ready(function(){
    sendPush()
    $(".modal").modal("show")
    $(".backup").hide()
    $(".finally").hide()
  });
  $('.key_feature').click(function(){
    $(".backup").show()
    $(".welcome").hide()
    $(".finally").hide()
  });
  $('.complete').click(function(){
    $(".backup").hide()
    $(".welcome").hide()
    $(".finally").show()
  });

$('#address_region').change(function() {
  region = $(this).val();
  $.ajax({
    url: '/get_cities',
    type: 'GET',
    data: {
      region: region
    },
    contentType: 'application/json',
    dataType: 'json',
    success: function(data) {
      $('#address_city').empty();
      $.each(data, function(id, value) {
        $('#address_city').append("<option value=" + value + ">" + value);
      });
    }
  });
});

</script>

<style type="text/css">
  .primary-text {
    float: left !important; 
    padding-right: 5px;
    box-sizing: border-box;
  }
  .pag_right_pa {
    position: relative;
    margin-left: 83%;
  }
  .form-btn-full {
    display: block;
    text-align: center;
    padding-top: 40px;
    box-sizing: border-box;
  }

  .form-group .col-md-6 label {
    font-size: 12px;
    display: block;
    text-align: left;
  }
  .form-group .col-md-6 input, .form-group .col-md-6 select {
    border: 1px solid #e1e1e1;
    border-radius: 0;
    display: block;
  }
  .finally {
    font-size: 28px;
    color: #0d70ae;
    font-weight: bold !important;
    margin-bottom: 30px;
  }
</style>

app/views/private/dashboard/notices.html.erb
<div class="screen__title">Notices</div>
<div class="row">
  <div class="screen__body col-md-12">
    <ul>
      <% @notices.each do |notice|%>
        <li>
          <%= notice.title%>
        </li>
      <%end%>
    </ul>
  </div>
</div>