config/routes.rb
Rails.application.routes.draw do

  post "/sendkeys" => "content#getJSON", :as => :getJSON
  post "/sendNo" => "content#sendPush", :as => :sendPush

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'admin/add_supplier_brand/:supplier_id/', to: 'admin/brands#add_supplier_brand', as: :add_supplier_brand
  get 'admin/new_supplier_brand/:supplier_id/', to: 'admin/brands#new_supplier_brand', as: :new_supplier_brand
  delete 'admin/remove_supplier_brand/:supplier_id/', to: 'admin/brands#remove_supplier_brand', as: :remove_supplier_brand

  delete 'admin/remove_supplier_category_part/:supplier_id/', to: 'admin/brands#remove_supplier_category_part', as: :remove_supplier_category_part

  post 'admin/add_supplier_category/:supplier_id/', to: 'admin/categories#add_supplier_category', as: :add_supplier_category
  get 'admin/new_supplier_category/:supplier_id/', to: 'admin/categories#new_supplier_category', as: :new_supplier_category
  delete 'admin/remove_supplier_category/:supplier_id/', to: 'admin/categories#remove_supplier_category', as: :remove_supplier_category

  post 'admin/add_user/:coupon_id/', to: 'admin/coupons#add_user', as: :add_user
  post 'admin/assign_all/:coupon_id/', to: 'admin/coupons#assign_all', as: :assign_all
  get 'admin/new_user_coupon/:coupon_id/', to: 'admin/coupons#new_user_coupon', as: :new_user_coupon
  delete 'admin/remove_coupon_user/:coupon_id/', to: 'admin/coupons#remove_coupon_user', as: :remove_coupon_user
  delete 'admin/category_sub_part_items/:category_sub_part_id', to: 'admin/category_part_items#destroy_category_sub_part', as: :remove_category_sub_part
  get 'open_image_to_process/:id', to: 'admin/item_types#open_image_to_process', as: :open_image_to_process
  
  get 'active/:id', to: 'admin/part_catalogs#active', as: :active
  get 'active_model/:id', to: 'admin/api_models#active_model', as: :active_model
  get 'active_part/:id', to: 'admin/api_parts#active_part', as: :active_part
  get 'open_image_to_process_part/:id', to: 'admin/api_parts#open_image_to_process_part', as: :open_image_to_process_part
  post 'create_hot_spot', to: 'admin/item_types#create_hot_spot', as: :create_hot_spot
  delete 'delete_hot_spot/:id', to: 'admin/item_types#delete_hot_spot', as: :delete_hot_spot
  
  get  '/', to: 'public/landing#index', as: :landing_index
  post  '/cotizar', to: 'public/landing#quote_create'
  get  '/quote', to: 'public/landing#quote', as: :landing_quote
  get  '/models', to: 'public/landing#models'
  get  '/get_models', to: 'public/landing#get_models'
  get  '/login_popup', to: 'public/landing#login_popup'
  get  '/get_fields', to: 'public/landing#get_fields'
  get  '/get_brands', to: 'public/landing#get_brands'
  get  '/get_date', to: 'public/landing#get_date'
  get  '/part_items', to: 'public/landing#part_items'
  get  '/category_parts', to: 'public/landing#category_parts'
  get  '/brands', to: 'public/landing#brands'
  post '/cotizar/ingreso', to: 'public/landing#quote_with_session', as: :landing_quote_with_session
  post '/login_with_address', to: 'public/landing#login_with_address', as: :landing_login_with_address
  post '/cotizar/registro', to: 'public/landing#quote_with_registration', as: :landing_quote_with_registration
  post '/cotizar/omniauth', to: 'public/landing#quote_with_omniauth', as: :landing_quote_with_omniauth
  post '/quote_with_current_user', to: 'public/landing#quote_with_current_user', as: :quote_with_current_user
  post '/create_quotation_request', to: 'public/landing#after_session_create_quotation_request'
  get 'get_item_sub_parts/', to: 'public/landing#category_sub_parts'
  get 'checkout/', to: 'public/landing#checkout'
  get 'cart/', to: 'public/landing#cart'
  get 'final_cart/', to: 'public/landing#final_cart'
  get 'remove_cart/', to: 'public/landing#remove_cart'
  get 'empty_cart/', to: 'public/landing#empty_cart'
  get 'update_quantity/', to: 'public/landing#update_quantity'
  get 'get_part_catalogs/', to: 'public/landing#get_part_catalogs'
  post 'checkout_process/', to: 'public/landing#checkout_process'
  post 'get_vehicle/', to: 'public/landing#get_vehicle'

  namespace :public, path: "" do 
    namespace :api do 
      resources :brands, only: [:index, :show]
      resources :models, only: [:index]
    end
  end

  namespace :api_data, path: "" do
    resources :catalogs
    resources :catalog_types
    resources :api_catalogs
    resources :api_models
    resources :api_sub_models
    resources :api_vehicles do
      collection do
        get 'user_vehicles'
      end
    end
    resources :api_vehicle_models
    resources :part_catalogs
    resources :api_parts do
      collection do
        get 'get_sub_part'
      end
    end
  end

  resources :category_part_items do
    get :autocomplete_category_part_item_name, :on => :collection
  end

  resources :vehicles
  resources :messages do 
    collection do 
      get :new_message
      post :send_message
    end
  end
  namespace :private, path: "" do 
    namespace :api do
      resources :quotations, only: [:index, :show]
      resources :quotation_requests do
        get "quotation_request_detail"
        resources :quotations, only: [:index, :show]
      end
      get 'get_user_vehicle', to: 'quotation_requests#get_user_vehicle'
      resources :users, only: [:index]
      #resources :suppliers_brands, only: [:index, :create, :destroy]

      get '/mi-perfil', to: 'profile#show', as: :profile_show
      post '/mi-perfil', to: 'profile#update', as: :profile_update
      get '/mi-perfil-edit', to: 'profile#edit', as: :profile_edit
      get '/new_address', to: 'profile#new_address', as: :new_address
      post '/create_address', to: 'profile#address_create', as: :create_address
      delete '/destroy_address/:id', to: 'profile#destroy_address', as: :destroy_address
      get '/update_password', to: 'profile#update_password', as: :update_password
      get '/edit_notify_preference', to: 'profile#edit_notify_preference', as: :edit_notify_preference
      post '/update_notify_preference', to: 'profile#update_notify_preference', as: :update_notify_preference
      get '/edit_address/:id', to: 'profile#edit_address', as: :edit_address
      post '/update_address/:id', to: 'profile#update_address', as: :update_address
      namespace :suppliers do 
        resources :brands, only: [:index, :create, :destroy, :new]
        resources :quotation_requests
        resources :quotations
        get '/approve_quote/:id', to: 'quotations#approve_quote', as: :approve_quote
      end
      get 'show_details/:id', to: 'quotations#show_details', as: :show_details
    end
  end

  namespace :employees, path: "" do
    resources :quotation_requests
    resources :quotations
  end

  devise_for :users, path: '/', path_names: { 
    sign_in: 'ingresar', 
    sign_out: 'salir', 
    registration: 'registro',
    sign_up: ''
  }, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    omniauth_callbacks: 'public/omniauth_callbacks',
    passwords: 'public/passwords'
  }
  devise_for :employees, path: '/', path_names: {
    sign_in: 'employee_sign_in',
    sign_out: 'employee_sign_out',
    registration: 'employee_registration'
  }, controllers: { 
    sessions: "employees/sessions",
    registrations: 'employees/registrations',
  }
  get '/employee_dashboard', to: 'employees/dashboard#index', as: :employee_dashboard

  get '/app', to: 'private/dashboard#index', as: :dashboard_index
  get '/notices', to: 'private/dashboard#notices', as: :notices
  get '/app/:some', to: 'private/dashboard#index'
  get '/app/:some/:some_again', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god/:how_the_fuck_i_do_a_wildcard', to: 'private/dashboard#index'

  resources :contacts

  resources :replies
  get 'how_its_works', to: 'pages#how_its_works'
  get 'about_us', to: 'pages#about_us'

  resources :questions do
    collection do
      get "show_pdf"
    end
    resources :replies
  end
  get 'all_questions', to: 'questions#all_questions'
  post 'filter_question', to: 'questions#filter_question'
  resources :quote_questions
  resources :referral_links
  resources :referral_users
  resources :orders do
    collection do
      get 'supplier_detail'
    end
  end

  resources :order_items, only:[] do
    get 'delivered'
    get 'approve'
    resources :courier_jobs, only: [:new, :create]
  end

  resources :courier_jobs, only: [:index, :edit, :update]
  resources :notifications, only: [:index]
  
  #****paypal******
  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
  get "paypal_payment" => "orders#paypal"

  #*****mercado_pago*** 
  get "mercado_proccess" => "orders#mercado_payment_proccess"
  post "/mercado_hook" => "orders#mercado_hook"
  get "mercado_return", to: "orders#mercado_return"

  #*****payment_notification****
  get "payment_method" => "orders#payment_method"
  get "payment_failed" => "orders#payment_failed"
  
  #******onepay****
  get "onepay" => "orders#onepay"
  get 'onepay_hook' => 'orders#onepay_hook'
  get 'commit' => 'orders#commit'

  #****carts****
  resources :carts
  get 'entrega', to: 'carts#entrega'
  post 'finalizar', to: 'carts#finalizar'
  get 'user_cart', to: 'carts#cart'
  get 'change_address', to: 'carts#change_address'
  get 'apply_coupon', to: 'carts#apply_coupon'
  get 'remove_coupon', to: 'carts#remove_coupon'
  get 'get_cities', to: 'carts#get_cities'
  delete 'delete_cart', to: 'carts#delete_cart'

end

app/models/quotation_request.rb
# == Schema Information
#
# Table name: quotation_requests
#
#  id         :bigint(8)        not null, primary key
#  status     :string           default("pending")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#
# Indexes
#
#  index_quotation_requests_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class QuotationRequest < ApplicationRecord
  paginates_per 20
  belongs_to :user
  has_many :quotation_request_parts, dependent: :destroy
  has_many :quotations
  has_many :messages
  has_many :notifications, as: :notifiable

  YEAR = (1950..2018).to_a.reverse
  STATUS = ['pending','in_process', 'approved', 'cancelled']

  scope :pending,   -> { where(status: 'pending')}
  scope :in_process,   -> { where(status: 'in_process')}
  scope :approved,   -> { where(status: 'approved')}
  scope :cancelled,   -> { where(status: 'cancelled')}
  
  scope :today, -> { where(created_at: Time.now.beginning_of_day..Time.now.end_of_day) }
  scope :this_week, -> { where(created_at: Time.now.beginning_of_week..Time.now.end_of_week) }
  scope :this_month, -> { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }
  scope :this_year, -> { where(created_at: Time.now.beginning_of_year..Time.now.end_of_year) }

  validates :status, inclusion: { in: STATUS, message: "Por favor proporcione un estado válido" }

  def as_json_summary
    parts_count = quotation_request_parts.count
    brand_list = quotation_request_parts.map { |it| it.model.brand.name }.uniq
    {
      id: self.id,
      created_at: self.created_at,
      brands: brand_list,
      parts_count: parts_count
    }
  end
end

app/controllers/employees/quotation_requests_controller.rb
class Employees::QuotationRequestsController < Employees::BaseController
 
  def index
    @quotations = QuotationRequest.all.order(created_at: :desc).page params[:page]
  end

  def show

  end
end

app/controllers/private/api/quotation_requests_controller.rb
class Private::Api::QuotationRequestsController < Private::BaseController
  include CreateQuotationRequest
  include CreateNotification
  layout 'v2_private'
  #include Paginate
  #before_action :set_pagination_defaults

  def index
    if params[:time].present? || params[:status].present?
      @quotation_requests = current_user.quotation_requests
      @quotation_requests = @quotation_requests if params[:time].blank? || params[:time] == "all"
      @quotation_requests = @quotation_requests.today if params[:time] == "today"
      @quotation_requests = @quotation_requests.this_week if params[:time] == "week"
      @quotation_requests = @quotation_requests.this_month if params[:time] == "month"
      @quotation_requests = @quotation_requests.this_year if params[:time] == "year"
      @quotation_requests = @quotation_requests.where(status: params[:status]) if params[:status].present?  && ['pending', 'in_process', 'approved'].include?(params[:status])
      
      @total_quotation_requests = @quotation_requests.order("created_at DESC")
    else
      @total_quotation_requests = current_user.quotation_requests.order("created_at DESC")
    end

    @quotation_requests = @total_quotation_requests.page params[:page]
    @pending_count = @total_quotation_requests.pending.count
    @quoted_count = @total_quotation_requests.in_process.count
    @approved_count = @total_quotation_requests.approved.count

    @question = Question.new
    @button = 'new_quotation'
    @notices = Notice.published.notice.mis_pedidos.last(5)
    @tips = Notice.published.tip.mis_pedidos.last(5)
  end

  def new
    @user_vehicles = ApiVehicle.where(user_id: current_user.id)
  end
  
  def show
    quot_request = current_user.quotation_requests.find(params[:id])
    if quot_request.present?
      @quotation_request = quot_request.load_parts
      @quotation_recived = quot_request.quotations
    else
      flash[:error] = "No record found!"
    end
  end

  def create
    begin
      @quotation_request = current_user.quotation_requests.create
      create_notification(@quotation_request.id,"quotation_request")
      @quotation_request.transaction do
        if params["vehicle-selection"] == "new_vehicle"
          vehicle = current_user.vehicles.new(vehicle_params)
          if vehicle.save
            vehicle_ids = [vehicle.id]
            create_items(vehicle_ids)
          end
        elsif params["vehicle-selection"] == "my_vehicle"
          vehicle_ids = params["vehicles"]["ids"]
          create_items(vehicle_ids)
        end
        redirect_to private_api_quotation_requests_path  
      end
      rescue ActiveRecord::RecordInvalid => invalid
    end
  end

  def create_items(vehicles)
    items_hash = eval(params["items"])
    request_items = []
    vehicles.each do |vehicle|
      items_hash.each do |item|
        item['vehicle_id'] = vehicle
        request_items << item
      end
    end
    @quotation_request.quotation_request_parts.create(request_items)
  end

  def edit
    @brands = Brand.pluck(:name, :id)
    @user_vehicles = current_user.vehicles
    # @quotation_request = current_user.quotation_requests.find(params[:id])
    # @quotation_request_part = @quotation_request.quotation_request_parts.last
    @quotation_request_part = QuotationRequestPart.find params[:id]
  end

  def update

    @quotation_request_part = QuotationRequestPart.find params[:id]

    pieces_params = params.permit(:description, :amount, :original, :alternative)
    
    #return if !pieces_params || pieces_params.size.zero?
    if @quotation_request_part.update_attributes(pieces_params)
      flash[:success] = "Quotation request updated successfully!"
      redirect_to private_api_quotation_requests_path
    end
    # ActiveRecord::Base.transaction do 
    #   pieces_params.map! do |part_params|
    #   end
    # end
  end

  def destroy
  end

  def get_user_vehicle
    @user_vehicles = current_user.vehicles.where(brand_id: params[:brand_id])
    data = [@user_vehicles.first.model_id, @user_vehicles.first.year, @user_vehicles.first.chasis_number]
    respond_to do |format|
      format.json { render json: data }
    end
  end
  
  def quotation_request_detail
    @request = QuotationRequest.find_by_id(params['quotation_request_id'])
    @request.quotations.update_all(flag: true) if @request.quotations.present?
    @quotation_requests = QuotationRequestPart.where(quotation_request_id: params[:quotation_request_id]).order(created_at: :desc).page params[:page]
    @vehicle = @quotation_requests.last.api_vehicle
    @question_count = @quotation_requests.last.questions.where(read: false).count if @quotation_requests.present?
  end

  def vehicle_params
    params.require(:vehicle).permit(:brand_id, :model_id, :chasis_number, :year, :patent)
  end
end

app/controllers/private/api/suppliers/brands_controller.rb
class Private::Api::Suppliers::BrandsController < Private::BaseController
  before_action :set_brand, only: [:create, :destroy]

  def index
    @supplier_brands = current_supplier.brands
    @brands = @supplier_brands.pluck(:name, :id)
  end

  def new
    
  end

  def create
    if @brand
      current_supplier.brands << @brand
      flash[:success] = "Brand added successfully!"
      redirect_to private_api_suppliers_brands_path
    else
      flash[:error] = "Brand could not added!"
      redirect_to private_api_suppliers_brands_path
    end
  end

  def destroy
    if @brand
      current_supplier.brands.delete @brand
      flash[:success] = "Brand deleted successfully!"
      redirect_to private_api_suppliers_brands_path
    else
      flash[:error] = "Brand could not deleted!"
      redirect_to private_api_suppliers_brands_path
    end
  end

  private

  def current_supplier
    current_user.suppliers.first
  end

  def set_brand
    @brand = Brand.find_by(id: params[:brand_id] || params[:id])
  end
end

app/helpers/employees/quotation_requests_helper.rb
module Employees::QuotationRequestsHelper
  
  def quotation_request_part_details quotation_request_id
    @quotation_request_parts = QuotationRequestPart.where(quotation_request_id: quotation_request_id)
  end
  def quotation_requests
    @quotation_requests = QuotationRequest.all
  end  
end

app/views/private/api/suppliers/quotation_requests/index.html.erb
<main id="main-container">
  <!-- Breadcrumb -->
  <div class="bg-body-light border-b">
    <div class="content py-5 text-center">
      <nav class="breadcrumb bg-body-light mb-0">
        <%= link_to "Escritorio", dashboard_index_path, class: "breadcrumb-item"%>
        <span class="breadcrumb-item active">Cotizaciones</span>
      </nav>
    </div>
  </div>
  <!-- END Breadcrumb -->
  <div class="content">
    <div class="content-heading">
      <div class="dropdown float-right">
        <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" id="ecom-orders-drop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= get_time_lable(params[:time]) %>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="ecom-orders-drop">
          <a class="dropdown-item active" href="<%= private_api_quotation_requests_path(:time => 'today', :status => params[:status]) %>">
            <i class="fa fa-fw fa-calendar mr-5"></i>Hoy
          </a>
          <a class="dropdown-item" href="<%= private_api_suppliers_quotation_requests_path(:time => 'week', :status => params[:status]) %>">
            <i class="fa fa-fw fa-calendar mr-5"></i>Esta semana
          </a>
          <a class="dropdown-item" href="<%= private_api_suppliers_quotation_requests_path(:time => 'month', :status => params[:status]) %>">
            <i class="fa fa-fw fa-calendar mr-5"></i>Este Mes
          </a>
          <a class="dropdown-item" href="<%= private_api_suppliers_quotation_requests_path(:time => 'year', :status => params[:status]) %>">
            <i class="fa fa-fw fa-calendar mr-5"></i>Este Año
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= private_api_suppliers_quotation_requests_path(:time => 'all', :status => params[:status]) %>">
            <i class="fa fa-fw fa-circle-o mr-5"></i>Todas
          </a>
        </div>
      </div>
      <div class="dropdown float-right mr-5">
        <button type="button" class="btn btn-sm btn-secondary dropdown-toggle" id="ecom-orders-filter-drop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= get_status_lable(params[:status]) %>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="ecom-orders-filter-drop">
          <a class="dropdown-item" href="<%= private_api_suppliers_quotation_requests_path(:status => 'pending', :time => params[:time]) %>">
            <i class="fa fa-fw fa-spinner fa-spin text-warning mr-5"></i>Pendientes
          </a>
          <a class="dropdown-item" href="<%= private_api_suppliers_quotation_requests_path(:status => 'in_process', :time => params[:time]) %>">
            <i class="fa fa-fw fa-refresh fa-spin text-info mr-5"></i>En Proceso
          </a>
          <a class="dropdown-item" href="<%= private_api_suppliers_quotation_requests_path(:status => 'approved', :time => params[:time]) %>">
            <i class="fa fa-fw fa-check text-success mr-5"></i>Aprobado
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item active" href="<%= private_api_suppliers_quotation_requests_path(:status => 'all', :time => params[:time]) %>">
            <i class="fa fa-fw fa-circle-o mr-5"></i>Todas
          </a>
        </div>
      </div>
      Cotizaciones(<%= @total_quotation_requests.count %>)
    </div>
    <div class="block block-rounded">
      <div class="block-content">
        <!-- Orders Table -->
        <div class="table-responsive">
          <table class="table table-borderless table-striped">
            <thead>
              <tr>
                <th class="text-center">Código</th>
                <th class="text-justify" style="width: 1px;">Estado</th>
                <th class="text-center">Fecha</th>
                <th class="text-center">Vehículo</th>
                <th class="text-center">Nº de Piezas</th>
                <th class="text-center"></th>
              </tr>
            </thead>
            <tbody>
              <% unless @quotation_requests.blank? %>
                <%@quotation_requests.each do |quotation_request|%>
                  <tr>
                    <td class="text-center">
                      <%= quotation_request.id%>
                    </td>
                    <td class="text-justify">
                      <span class="badge badge-<%= bootstrap_class_for(quotation_request.status)%>"><%= translate_for(quotation_request.status) %></span>
                    </td>
                    <td class="text-center">
                      <%= quotation_request.created_at.strftime('%d/%m/%Y') rescue ''%>
                    </td>
                    <td class="text-center">
                      <%= QuotationRequestPart.vehicle_model_name(quotation_request.id) %>
                    </td>
                    <td class="text-center">
                      <%= quotation_request.quotation_request_parts.count %>
                    </td>
                    <td class="text-center">
                      <%= link_to private_api_suppliers_quotation_request_path(quotation_request.id) do %>
                        Ver detalle
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% else %>
                <tr><td class="text-center" colspan="6">ningún record fue encontrado</td></tr>
              <% end %>
              <tr>
                <td colspan="6">
                  <%= paginate @quotation_requests %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>