config/routes.rb
Rails.application.routes.draw do

  post "/sendkeys" => "content#getJSON", :as => :getJSON
  post "/sendNo" => "content#sendPush", :as => :sendPush

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  post 'admin/add_supplier_brand/:supplier_id/', to: 'admin/brands#add_supplier_brand', as: :add_supplier_brand
  get 'admin/new_supplier_brand/:supplier_id/', to: 'admin/brands#new_supplier_brand', as: :new_supplier_brand
  delete 'admin/remove_supplier_brand/:supplier_id/', to: 'admin/brands#remove_supplier_brand', as: :remove_supplier_brand

  delete 'admin/remove_supplier_category_part/:supplier_id/', to: 'admin/brands#remove_supplier_category_part', as: :remove_supplier_category_part

  post 'admin/add_supplier_category/:supplier_id/', to: 'admin/categories#add_supplier_category', as: :add_supplier_category
  get 'admin/new_supplier_category/:supplier_id/', to: 'admin/categories#new_supplier_category', as: :new_supplier_category
  delete 'admin/remove_supplier_category/:supplier_id/', to: 'admin/categories#remove_supplier_category', as: :remove_supplier_category

  post 'admin/add_user/:coupon_id/', to: 'admin/coupons#add_user', as: :add_user
  post 'admin/assign_all/:coupon_id/', to: 'admin/coupons#assign_all', as: :assign_all
  get 'admin/new_user_coupon/:coupon_id/', to: 'admin/coupons#new_user_coupon', as: :new_user_coupon
  delete 'admin/remove_coupon_user/:coupon_id/', to: 'admin/coupons#remove_coupon_user', as: :remove_coupon_user
  delete 'admin/category_sub_part_items/:category_sub_part_id', to: 'admin/category_part_items#destroy_category_sub_part', as: :remove_category_sub_part
  get 'open_image_to_process/:id', to: 'admin/item_types#open_image_to_process', as: :open_image_to_process
  
  get 'active/:id', to: 'admin/part_catalogs#active', as: :active
  get 'active_model/:id', to: 'admin/api_models#active_model', as: :active_model
  get 'active_part/:id', to: 'admin/api_parts#active_part', as: :active_part
  get 'open_image_to_process_part/:id', to: 'admin/api_parts#open_image_to_process_part', as: :open_image_to_process_part
  post 'create_hot_spot', to: 'admin/item_types#create_hot_spot', as: :create_hot_spot
  delete 'delete_hot_spot/:id', to: 'admin/item_types#delete_hot_spot', as: :delete_hot_spot
  
  get  '/', to: 'public/landing#index', as: :landing_index
  post  '/cotizar', to: 'public/landing#quote_create'
  get  '/quote', to: 'public/landing#quote', as: :landing_quote
  get  '/models', to: 'public/landing#models'
  get  '/get_models', to: 'public/landing#get_models'
  get  '/login_popup', to: 'public/landing#login_popup'
  get  '/get_fields', to: 'public/landing#get_fields'
  get  '/get_brands', to: 'public/landing#get_brands'
  get  '/get_date', to: 'public/landing#get_date'
  get  '/part_items', to: 'public/landing#part_items'
  get  '/category_parts', to: 'public/landing#category_parts'
  get  '/brands', to: 'public/landing#brands'
  post '/cotizar/ingreso', to: 'public/landing#quote_with_session', as: :landing_quote_with_session
  post '/login_with_address', to: 'public/landing#login_with_address', as: :landing_login_with_address
  post '/cotizar/registro', to: 'public/landing#quote_with_registration', as: :landing_quote_with_registration
  post '/cotizar/omniauth', to: 'public/landing#quote_with_omniauth', as: :landing_quote_with_omniauth
  post '/quote_with_current_user', to: 'public/landing#quote_with_current_user', as: :quote_with_current_user
  post '/create_quotation_request', to: 'public/landing#after_session_create_quotation_request'
  get 'get_item_sub_parts/', to: 'public/landing#category_sub_parts'
  get 'checkout/', to: 'public/landing#checkout'
  get 'cart/', to: 'public/landing#cart'
  get 'final_cart/', to: 'public/landing#final_cart'
  get 'remove_cart/', to: 'public/landing#remove_cart'
  get 'empty_cart/', to: 'public/landing#empty_cart'
  get 'update_quantity/', to: 'public/landing#update_quantity'
  get 'get_part_catalogs/', to: 'public/landing#get_part_catalogs'
  post 'checkout_process/', to: 'public/landing#checkout_process'
  post 'get_vehicle/', to: 'public/landing#get_vehicle'

  namespace :public, path: "" do 
    namespace :api do 
      resources :brands, only: [:index, :show]
      resources :models, only: [:index]
    end
  end

  namespace :api_data, path: "" do
    resources :catalogs
    resources :catalog_types
    resources :api_catalogs
    resources :api_models
    resources :api_sub_models
    resources :api_vehicles do
      collection do
        get 'user_vehicles'
      end
    end
    resources :api_vehicle_models
    resources :part_catalogs
    resources :api_parts do
      collection do
        get 'get_sub_part'
      end
    end
  end

  resources :category_part_items do
    get :autocomplete_category_part_item_name, :on => :collection
  end

  resources :vehicles
  resources :messages do 
    collection do 
      get :new_message
      post :send_message
    end
  end
  namespace :private, path: "" do 
    namespace :api do
      resources :quotations, only: [:index, :show]
      resources :quotation_requests do
        get "quotation_request_detail"
        resources :quotations, only: [:index, :show]
      end
      get 'get_user_vehicle', to: 'quotation_requests#get_user_vehicle'
      resources :users, only: [:index]
      #resources :suppliers_brands, only: [:index, :create, :destroy]

      get '/mi-perfil', to: 'profile#show', as: :profile_show
      post '/mi-perfil', to: 'profile#update', as: :profile_update
      get '/mi-perfil-edit', to: 'profile#edit', as: :profile_edit
      get '/new_address', to: 'profile#new_address', as: :new_address
      post '/create_address', to: 'profile#address_create', as: :create_address
      delete '/destroy_address/:id', to: 'profile#destroy_address', as: :destroy_address
      get '/update_password', to: 'profile#update_password', as: :update_password
      get '/edit_notify_preference', to: 'profile#edit_notify_preference', as: :edit_notify_preference
      post '/update_notify_preference', to: 'profile#update_notify_preference', as: :update_notify_preference
      get '/edit_address/:id', to: 'profile#edit_address', as: :edit_address
      post '/update_address/:id', to: 'profile#update_address', as: :update_address
      namespace :suppliers do 
        resources :brands, only: [:index, :create, :destroy, :new]
        resources :quotation_requests
        resources :quotations
        get '/approve_quote/:id', to: 'quotations#approve_quote', as: :approve_quote
      end
      get 'show_details/:id', to: 'quotations#show_details', as: :show_details
    end
  end

  namespace :employees, path: "" do
    resources :quotation_requests
    resources :quotations
  end

  devise_for :users, path: '/', path_names: { 
    sign_in: 'ingresar', 
    sign_out: 'salir', 
    registration: 'registro',
    sign_up: ''
  }, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    omniauth_callbacks: 'public/omniauth_callbacks',
    passwords: 'public/passwords'
  }
  devise_for :employees, path: '/', path_names: {
    sign_in: 'employee_sign_in',
    sign_out: 'employee_sign_out',
    registration: 'employee_registration'
  }, controllers: { 
    sessions: "employees/sessions",
    registrations: 'employees/registrations',
  }
  get '/employee_dashboard', to: 'employees/dashboard#index', as: :employee_dashboard

  get '/app', to: 'private/dashboard#index', as: :dashboard_index
  get '/notices', to: 'private/dashboard#notices', as: :notices
  get '/app/:some', to: 'private/dashboard#index'
  get '/app/:some/:some_again', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god', to: 'private/dashboard#index'
  get '/app/:some/:some_again/:oh_god/:how_the_fuck_i_do_a_wildcard', to: 'private/dashboard#index'

  resources :contacts

  resources :replies
  get 'how_its_works', to: 'pages#how_its_works'
  get 'about_us', to: 'pages#about_us'

  resources :questions do
    collection do
      get "show_pdf"
    end
    resources :replies
  end
  get 'all_questions', to: 'questions#all_questions'
  post 'filter_question', to: 'questions#filter_question'
  resources :quote_questions
  resources :referral_links
  resources :referral_users
  resources :orders do
    collection do
      get 'supplier_detail'
    end
  end

  resources :order_items, only:[] do
    get 'delivered'
    get 'approve'
    resources :courier_jobs, only: [:new, :create]
  end

  resources :courier_jobs, only: [:index, :edit, :update]
  resources :notifications, only: [:index]
  
  #****paypal******
  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
  get "paypal_payment" => "orders#paypal"

  #*****mercado_pago*** 
  get "mercado_proccess" => "orders#mercado_payment_proccess"
  post "/mercado_hook" => "orders#mercado_hook"
  get "mercado_return", to: "orders#mercado_return"

  #*****payment_notification****
  get "payment_method" => "orders#payment_method"
  get "payment_failed" => "orders#payment_failed"
  
  #******onepay****
  get "onepay" => "orders#onepay"
  get 'onepay_hook' => 'orders#onepay_hook'
  get 'commit' => 'orders#commit'

  #****carts****
  resources :carts
  get 'entrega', to: 'carts#entrega'
  post 'finalizar', to: 'carts#finalizar'
  get 'user_cart', to: 'carts#cart'
  get 'change_address', to: 'carts#change_address'
  get 'apply_coupon', to: 'carts#apply_coupon'
  get 'remove_coupon', to: 'carts#remove_coupon'
  get 'get_cities', to: 'carts#get_cities'
  delete 'delete_cart', to: 'carts#delete_cart'

end

app/controllers/employees/base_controller.rb
class Employees::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_for

  protected

  def layout_for
    current_employee ? 'employee_dashboard' : 'employee'
  end

  def set_pagination_defaults
    @per_page = params[:per_page]&.to_i || 10
    @page = params[:page]&.to_i || 1
  end
end

app/controllers/employees/confirmations_controller.rb
# frozen_string_literal: true

class Employees::ConfirmationsController < Devise::ConfirmationsController
  layout 'employee_dashboard'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/dashboard_controller.rb
class Employees::DashboardController < Employees::BaseController
  
  def index

  end
end

app/controllers/employees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'employee'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
# frozen_string_literal: true

class Employees::PasswordsController < Devise::PasswordsController
  layout 'employee_dashboard'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/quotation_requests_controller.rb
class Employees::QuotationRequestsController < Employees::BaseController
 
  def index
    @quotations = QuotationRequest.all.order(created_at: :desc).page params[:page]
  end

  def show

  end
end

app/controllers/employees/quotations_controller.rb
class Employees::QuotationsController < Employees::BaseController

  def index
  end

  def show
    @quotation_request_parts = QuotationRequestPart.where(quotation_request_id: params[:id])
  end
  
end

app/controllers/employees/registrations_controller.rb
# frozen_string_literal: true

class Employees::RegistrationsController < Devise::RegistrationsController
  layout :layout_for
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def layout_for
    current_employee ? 'employee_dashboard' : 'employee'
  end
end

app/controllers/employees/sessions_controller.rb
# frozen_string_literal: true
class Employees::SessionsController < Devise::SessionsController
  layout :layout_for
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   @resource = Employee.new
  #   super
  # end

  # POST /resource/sign_in
  def create
    employee = Employee.find_by(email:employee_params[:email])
    valid_privilege = employee&.valid_privilege?
    if valid_privilege
      valid_password = employee&.valid_password?(employee_params[:password])
      if !employee or !valid_password
        @resource = Employee.new(employee_params)
        flash[:error] = "Correo electrónico o contraseña inválido"
        redirect_to new_employee_session_path
      else
        super
      end
    else
      flash[:error] = "No access permission or Not registred yet!"
      redirect_to new_employee_session_path
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    "/employee_dashboard"
  end
  
  def employee_params
    params.require(:employee).permit(:email, :password)
  end

  def layout_for
    current_employee ? 'employee_dashboard' : 'employee'
  end
end

app/controllers/employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  layout 'employee_dashboard'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/employees/quotation_requests_helper.rb
module Employees::QuotationRequestsHelper
  
  def quotation_request_part_details quotation_request_id
    @quotation_request_parts = QuotationRequestPart.where(quotation_request_id: quotation_request_id)
  end
  def quotation_requests
    @quotation_requests = QuotationRequest.all
  end  
end

app/helpers/employees/quotations_helper.rb
module Employees::QuotationsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/layouts/employee/_footer.html.erb
<div class="footer">
  <div class="wrapper__container">
    <div class="footer__content">
      <div class="footer__row">
        <div class="footer__row__col">
          <div class="footer__brand">INPARTS</div>
        </div>

        <div class="footer__row__col">
          <div class="footer__title">ENLACES</div>  
          <div class="footer__list">
            <div class="footer__list__item"><a href="#" class="footer__list__item__action">Acerca de nosotros</a></div>
            <div class="footer__list__item"><a href="#" class="footer__list__item__action">Cómo funciona</a></div>
            <div class="footer__list__item"><a href="#" class="footer__list__item__action">Proveedores</a></div>
            <div class="footer__list__item"><a href="#" class="footer__list__item__action">Contacto</a></div>
          </div>
        </div>
        
        <div class="footer__row__col">
          <div class="footer__title">CONTACTO</div>
          <div class="footer-card">
            <div class="footer-card__image">
              <%= fa_icon "phone", class: "footer-card__image__icon" %>
            </div>

            <div class="footer-card__content">
              <div class="footer-card__content__title">Teléfono:</div>
              <div class="footer-card__content__value">+569 9 8505 1046</div>
            </div>
          </div>

          <div class="footer-card">
            <div class="footer-card__image">
              <%= fa_icon "envelope", class: "footer-card__image__icon" %>
            </div>

            <div class="footer-card__content">
              <div class="footer-card__content__title">Email:</div>
              <div class="footer-card__content__value">contacto@inparts.cl</div>
            </div>
          </div>
        </div>

        <div class="footer__row__col">
          <div class="footer__title">SÍGUENOS</div>
            <div class="footer-social">
              <div class="footer-social__image">
                <a href="#"><div class="footer-social__image__facebook"></div></a>
                <a href="#"><div class="footer-social__image__tweeter"></div></a>
                <a href="#"><div class="footer-social__image__google"></div></a>
                <a href="#"><div class="footer-social__image__instagram"></div></a>
              </div>
            </div>
            <div class="footer-social">
              <div class="footer-social__webpay"></div>
            </div>
          </div>
        </div>
      </div>
    <div class="footer__bottom">
      © 2018. TODOS LOS DERECHOS RESERVADOS.
    </div>
  </div>

  <div id="footer-scroll"></div>
</div>

app/views/layouts/employee/_header.html.erb
<div class="header">
  <div class="header__container wrapper__container">
    <div class="header__left">
      <div class="header__brand brand">INPARTS</div>
      <div class="header__toggle"></div>
    </div>
    
    <div class="header__right">
      <div class="header__nav">
        <div class="header__nav__item"><%= link_to 'NOSOTROS', about_us_path, class: "header__nav__item__link"%></div>
        <div class="header__nav__item"><%= link_to 'CÓMO FUNCIONA', how_its_works_path, class: "header__nav__item__link"%></div>
        <div class="header__nav__item"><a class="header__nav__item__link" href="">PROVEEDORES</a></div>
        <div class="header__nav__item"><%= link_to 'CONTÁCTANOS', contacts_path(), class: "header__nav__item__link" %></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/employee/_preheader.html.erb
<div class="preheader">
  <div class="wrapper__container preheader__container">
    <div class="preheader__nav">
      <% unless current_employee %>
        <div class="preheader__nav__item">
          <%= link_to new_employee_session_path, class: "preheader__nav__item__action" do %>
            <%= fa_icon "unlock" %>
              Ingresar
          <% end %>
        </div>

        <div class="preheader__nav__item">
          <%= link_to new_employee_registration_path, class: "preheader__nav__item__action preheader__nav__item__action--orange" do %>
            <%= fa_icon "user" %>
              Registro
          <% end %>
        </div>
      <% else %>
        <div class="preheader__nav__item">
          <%= link_to employee_dashboard_path, class: "preheader__nav__item__action preheader__nav__item__action--orange" do %><%= fa_icon "user" %> Mi cuenta
          <% end %>
        </div>

        <div class="preheader__nav__item">
          <%= link_to destroy_employee_session_path, class: "preheader__nav__item__action" do %><%= fa_icon "sign-out" %> Cerrar sesión<% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>